project_id = "jmnyaudcgdanpgctroko"

[functions.gasless-transfer]
verify_jwt = false

[functions.gasless-solana]
verify_jwt = false

[functions.gasless-evm]
verify_jwt = false

[functions.gasless-sui]
verify_jwt = false

[functions.get-token-prices]
verify_jwt = false

[functions.search-tokens]
verify_jwt = false

[functions.bungee-incognito]
verify_jwt = false

[functions.discover-tokens]
verify_jwt = false
