project_id = "jmnyaudcgdanpgctroko"

[functions.gasless-transfer]
verify_jwt = false

[functions.get-token-prices]
verify_jwt = false

[functions.search-tokens]
verify_jwt = false

[functions.discover-solana-tokens]
verify_jwt = false

[functions.record-swap]
verify_jwt = false

[functions.paj-cash]
verify_jwt = false

[functions.paj-webhook]
verify_jwt = false
